<a href="https://colab.research.google.com/github/NavyaRamesh-01/Course-Recommendation-System/blob/main/Course_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
juliasevaslidou_coursera_courses_metadata_and_reviews_dataset_2025_path = kagglehub.dataset_download('juliasevaslidou/coursera-courses-metadata-and-reviews-dataset-2025')

print('Data source import complete.')

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (0.4.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/juliasevaslidou/coursera-courses-metadata-and-reviews-dataset-2025?dataset_version_number=1...

100%|██████████| 41.6M/41.6M [00:00<00:00, 56.8MB/s]

Extracting files...

Data source import complete.

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
import os

path = juliasevaslidou_coursera_courses_metadata_and_reviews_dataset_2025_path

courses_file = os.path.join(path, 'coursera_courses_metadata2025.csv')
reviews_file = os.path.join(path, 'coursera_reviews2025.csv')

courses = pd.read_csv(courses_file)
reviews = pd.read_csv(reviews_file)

print("Files loaded successfully from Colab's local storage!")

Files loaded successfully from Colab's local storage!

In [4]:
courses.head()

,url,slug,type,title,description,provider,instructors,language,level,rating,ratingCount,timeRequired,workload,keywords,skills,lastScrapedAt
0,https://www.coursera.org/learn/machine-learning,machine-learning,course,Supervised Machine Learning: Regression and Cl...,In the first course of the Machine Learning Sp...,DeepLearning.AI,NaN,NaN,Beginner,"4,8974551877535",30572.0,NaN,NaN,NaN,"[""Jupyter"", ""Predictive Modeling"", ""Python Pro...",2025-10-17T08:18:58Z
1,https://www.coursera.org/learn/indigenous-canada,indigenous-canada,course,Indigenous Canada,Indigenous Canada is a 12-lesson Massive Open ...,University of Alberta,NaN,NaN,Mixed,"4,81846835335207",23478.0,NaN,NaN,NaN,"[""Socioeconomics"", ""Governance"", ""Political Sc...",2025-10-17T08:18:59Z
2,https://www.coursera.org/learn/the-science-of-...,the-science-of-well-being,course,The Science of Well-Being,NEW TEEN VERSION AVAILABLE HERE: https://www.c...,Yale University,NaN,NaN,Mixed,"4,89704848910752",39844.0,NaN,NaN,NaN,"[""Growth Mindedness"", ""Cognitive Behavioral Th...",2025-10-17T08:19:02Z
3,https://www.coursera.org/learn/technical-suppo...,technical-support-fundamentals,course,Technical Support Fundamentals,"In this course, youâll be introduced to the ...",Google,NaN,NaN,Beginner,"4,82638618601921",161865.0,NaN,NaN,NaN,"[""Hardware Troubleshooting"", ""System Software""...",2025-10-17T08:19:04Z
4,https://www.coursera.org/learn/google-cbrs-cpi...,google-cbrs-cpi-training,course,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[""Public Key Infrastructure"", ""System Configur...",2025-10-17T08:19:05Z

In [5]:
reviews.head()

,url,slug,type,courseId,reviewId,rating,createdAt,language,reviewer,title,text,helpfulCount,responseCount,source,lastScrapedAt
0,https://www.coursera.org/learn/aboriginal-educ...,aboriginal-education,course,o_uax8a6EeWIJRKecECAWw,NaN,2,"Jun 3, 2020",NaN,Colleen T,NaN,This course is quite short and does not includ...,NaN,NaN,html-fallback,2025-08-20T19:03:04Z
1,https://www.coursera.org/learn/aboriginal-educ...,aboriginal-education,course,o_uax8a6EeWIJRKecECAWw,NaN,1,"May 22, 2020",NaN,Colton W,NaN,This course has great intentions and decent co...,NaN,NaN,html-fallback,2025-08-20T19:03:04Z
2,https://www.coursera.org/learn/aboriginal-educ...,aboriginal-education,course,o_uax8a6EeWIJRKecECAWw,NaN,2,"May 7, 2019",NaN,Kinusan D S,NaN,"This course is outdated, material needs to be ...",NaN,NaN,html-fallback,2025-08-20T19:03:04Z
3,https://www.coursera.org/learn/aboriginal-educ...,aboriginal-education,course,o_uax8a6EeWIJRKecECAWw,NaN,5,"Nov 7, 2021",NaN,Joan B,NaN,I found this course informative and enlighteni...,NaN,NaN,html-fallback,2025-08-20T19:03:04Z
4,https://www.coursera.org/learn/aboriginal-educ...,aboriginal-education,course,o_uax8a6EeWIJRKecECAWw,NaN,5,"Aug 22, 2018",NaN,Mandy A,NaN,A fantastic course. I learnt so much and the i...,NaN,NaN,html-fallback,2025-08-20T19:03:04Z

In [6]:
courses.isna().sum()

url                0
slug               0
type               0
title            131
description       81
provider         131
instructors      625
language         625
level            131
rating           131
ratingCount      131
timeRequired     625
workload         625
keywords         625
skills            55
lastScrapedAt      0
dtype: int64

In [7]:
courses=courses[['url','slug','title','description','provider','level','rating','ratingCount','skills']]

In [8]:
reviews.isna().sum()

url                   0
slug                  0
type                  0
courseId              0
reviewId         691594
rating                0
createdAt             0
language         691594
reviewer              3
title            691594
text                167
helpfulCount     691594
responseCount    691594
source                0
lastScrapedAt         0
dtype: int64

In [9]:
reviews=reviews[['url','slug','rating','reviewer','text']]

In [10]:
avg_ratings_by_course = reviews.groupby(['url', 'slug'])['rating'].mean().reset_index()
avg_ratings_by_course.rename(columns={'rating': 'average_rating'}, inplace=True)

In [11]:
avg_ratings_by_course.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             565 non-null    object
 1   slug            565 non-null    object
 2   average_rating  565 non-null    float64
dtypes: float64(1), object(2)
memory usage: 13.4+ KB

In [12]:
courses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   url          625 non-null    object
 1   slug         625 non-null    object
 2   title        494 non-null    object
 3   description  544 non-null    object
 4   provider     494 non-null    object
 5   level        494 non-null    object
 6   rating       494 non-null    object
 7   ratingCount  494 non-null    float64
 8   skills       570 non-null    object
dtypes: float64(1), object(8)
memory usage: 44.1+ KB

In [13]:
course_ratings=courses.merge(avg_ratings_by_course,on='url',how='left')

In [14]:
course_ratings.isna().sum()

url                 0
slug_x              0
title             131
description        81
provider          131
level             131
rating            131
ratingCount       131
skills             55
slug_y             60
average_rating     60
dtype: int64

In [15]:
course_ratings['final_title']=course_ratings['title'].fillna(course_ratings['slug_x'].str.replace('-', ' '))
course_ratings

,url,slug_x,title,description,provider,level,rating,ratingCount,skills,slug_y,average_rating,final_title
0,https://www.coursera.org/learn/machine-learning,machine-learning,Supervised Machine Learning: Regression and Cl...,In the first course of the Machine Learning Sp...,DeepLearning.AI,Beginner,"4,8974551877535",30572.0,"[""Jupyter"", ""Predictive Modeling"", ""Python Pro...",machine-learning,4.973494,Supervised Machine Learning: Regression and Cl...
1,https://www.coursera.org/learn/indigenous-canada,indigenous-canada,Indigenous Canada,Indigenous Canada is a 12-lesson Massive Open ...,University of Alberta,Mixed,"4,81846835335207",23478.0,"[""Socioeconomics"", ""Governance"", ""Political Sc...",indigenous-canada,4.965189,Indigenous Canada
2,https://www.coursera.org/learn/the-science-of-...,the-science-of-well-being,The Science of Well-Being,NEW TEEN VERSION AVAILABLE HERE: https://www.c...,Yale University,Mixed,"4,89704848910752",39844.0,"[""Growth Mindedness"", ""Cognitive Behavioral Th...",the-science-of-well-being,4.939234,The Science of Well-Being
3,https://www.coursera.org/learn/technical-suppo...,technical-support-fundamentals,Technical Support Fundamentals,"In this course, youâll be introduced to the ...",Google,Beginner,"4,82638618601921",161865.0,"[""Hardware Troubleshooting"", ""System Software""...",technical-support-fundamentals,4.968825,Technical Support Fundamentals
4,https://www.coursera.org/learn/google-cbrs-cpi...,google-cbrs-cpi-training,NaN,NaN,NaN,NaN,NaN,NaN,"[""Public Key Infrastructure"", ""System Configur...",google-cbrs-cpi-training,4.103896,google cbrs cpi training
...,...,...,...,...,...,...,...,...,...,...,...,...
620,https://www.coursera.org/learn/accounting-data...,accounting-data-analytics-python,Accounting Data Analytics with Python,This course focuses on developing Python skill...,University of Illinois Urbana-Champaign,Intermediate,"4,41284403669725",109.0,"[""Matplotlib"", ""Business Analysis"", ""Python Pr...",accounting-data-analytics-python,4.093750,Accounting Data Analytics with Python
621,https://www.coursera.org/learn/spectroscopy,spectroscopy,Introduction to Molecular Spectroscopy,The course introduces the three key spectrosco...,University of Manchester,Intermediate,"4,70480549199085",2622.0,"[""Physics"", ""Chemistry"", ""Laboratory Technique...",spectroscopy,4.640244,Introduction to Molecular Spectroscopy
622,https://www.coursera.org/learn/managing-as-a-c...,managing-as-a-coach,Managing as a Coach,Do you (or do you want to) manage employees? H...,"University of California, Davis",Mixed,"4,78919160339437",2239.0,"[""Self-Awareness"", ""Coaching"", ""Mentorship"", ""...",managing-as-a-coach,4.815152,Managing as a Coach
623,https://www.coursera.org/learn/hotel-distribution,hotel-distribution,NaN,NaN,NaN,NaN,NaN,NaN,"[""Strategic Partnership"", ""Business Modeling"",...",hotel-distribution,4.610951,hotel distribution
624,https://www.coursera.org/learn/data-science-co...,data-science-course,NaN,NaN,NaN,NaN,NaN,NaN,"[""Data Management"", ""Project Design"", ""Perform...",data-science-course,4.458746,data science course

In [16]:
course_ratings['rating']=course_ratings['rating'].str.replace(',','.')

In [17]:
course_ratings['rating']=pd.to_numeric(course_ratings['rating'], errors='coerce')

In [18]:
course_ratings['rating']

0      4.897455
1      4.818468
2      4.897048
3      4.826386
4           NaN
         ...
620    4.412844
621    4.704805
622    4.789192
623         NaN
624         NaN
Name: rating, Length: 625, dtype: float64

In [19]:
course_ratings['final_rating']=course_ratings['rating'].fillna(course_ratings['average_rating'])
course_ratings

,url,slug_x,title,description,provider,level,rating,ratingCount,skills,slug_y,average_rating,final_title,final_rating
0,https://www.coursera.org/learn/machine-learning,machine-learning,Supervised Machine Learning: Regression and Cl...,In the first course of the Machine Learning Sp...,DeepLearning.AI,Beginner,4.897455,30572.0,"[""Jupyter"", ""Predictive Modeling"", ""Python Pro...",machine-learning,4.973494,Supervised Machine Learning: Regression and Cl...,4.897455
1,https://www.coursera.org/learn/indigenous-canada,indigenous-canada,Indigenous Canada,Indigenous Canada is a 12-lesson Massive Open ...,University of Alberta,Mixed,4.818468,23478.0,"[""Socioeconomics"", ""Governance"", ""Political Sc...",indigenous-canada,4.965189,Indigenous Canada,4.818468
2,https://www.coursera.org/learn/the-science-of-...,the-science-of-well-being,The Science of Well-Being,NEW TEEN VERSION AVAILABLE HERE: https://www.c...,Yale University,Mixed,4.897048,39844.0,"[""Growth Mindedness"", ""Cognitive Behavioral Th...",the-science-of-well-being,4.939234,The Science of Well-Being,4.897048
3,https://www.coursera.org/learn/technical-suppo...,technical-support-fundamentals,Technical Support Fundamentals,"In this course, youâll be introduced to the ...",Google,Beginner,4.826386,161865.0,"[""Hardware Troubleshooting"", ""System Software""...",technical-support-fundamentals,4.968825,Technical Support Fundamentals,4.826386
4,https://www.coursera.org/learn/google-cbrs-cpi...,google-cbrs-cpi-training,NaN,NaN,NaN,NaN,NaN,NaN,"[""Public Key Infrastructure"", ""System Configur...",google-cbrs-cpi-training,4.103896,google cbrs cpi training,4.103896
...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,https://www.coursera.org/learn/accounting-data...,accounting-data-analytics-python,Accounting Data Analytics with Python,This course focuses on developing Python skill...,University of Illinois Urbana-Champaign,Intermediate,4.412844,109.0,"[""Matplotlib"", ""Business Analysis"", ""Python Pr...",accounting-data-analytics-python,4.093750,Accounting Data Analytics with Python,4.412844
621,https://www.coursera.org/learn/spectroscopy,spectroscopy,Introduction to Molecular Spectroscopy,The course introduces the three key spectrosco...,University of Manchester,Intermediate,4.704805,2622.0,"[""Physics"", ""Chemistry"", ""Laboratory Technique...",spectroscopy,4.640244,Introduction to Molecular Spectroscopy,4.704805
622,https://www.coursera.org/learn/managing-as-a-c...,managing-as-a-coach,Managing as a Coach,Do you (or do you want to) manage employees? H...,"University of California, Davis",Mixed,4.789192,2239.0,"[""Self-Awareness"", ""Coaching"", ""Mentorship"", ""...",managing-as-a-coach,4.815152,Managing as a Coach,4.789192
623,https://www.coursera.org/learn/hotel-distribution,hotel-distribution,NaN,NaN,NaN,NaN,NaN,NaN,"[""Strategic Partnership"", ""Business Modeling"",...",hotel-distribution,4.610951,hotel distribution,4.610951
624,https://www.coursera.org/learn/data-science-co...,data-science-course,NaN,NaN,NaN,NaN,NaN,NaN,"[""Data Management"", ""Project Design"", ""Perform...",data-science-course,4.458746,data science course,4.458746

In [20]:
course_ratings['final_rating']=course_ratings['final_rating'].round(2)

In [21]:
course_ratings['final_rating']

0      4.90
1      4.82
2      4.90
3      4.83
4      4.10
       ...
620    4.41
621    4.70
622    4.79
623    4.61
624    4.46
Name: final_rating, Length: 625, dtype: float64

In [22]:
course_ratings.isna().sum()

url                 0
slug_x              0
title             131
description        81
provider          131
level             131
rating            131
ratingCount       131
skills             55
slug_y             60
average_rating     60
final_title         0
final_rating       57
dtype: int64

In [23]:
course_ratings=course_ratings[['url','slug_x','final_title','description','level','skills','final_rating']]

In [24]:
course_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   url           625 non-null    object
 1   slug_x        625 non-null    object
 2   final_title   625 non-null    object
 3   description   544 non-null    object
 4   level         494 non-null    object
 5   skills        570 non-null    object
 6   final_rating  568 non-null    float64
dtypes: float64(1), object(6)
memory usage: 34.3+ KB

In [25]:
course_ratings.isna().sum()

url               0
slug_x            0
final_title       0
description      81
level           131
skills           55
final_rating     57
dtype: int64

In [26]:
course_ratings['level'].value_counts()

level
Beginner        263
Mixed           130
Intermediate     93
Advanced          8
Name: count, dtype: int64

In [27]:
course_ratings['description'].fillna('No description',inplace=True)
course_ratings['level'].fillna(course_ratings['level'].mode()[0],inplace=True)
course_ratings['final_rating'].fillna(course_ratings['final_rating'].mean(),inplace=True)

In [28]:
import ast

In [29]:
def remove_spaces(obj):
    l=[]
    if pd.isna(obj) or obj is None:
        return []
    for i in ast.literal_eval(obj):
        l.append(i.replace(' ',''))
    return l

In [30]:
course_ratings['skills']=course_ratings['skills'].apply(remove_spaces)

In [31]:
course_ratings.isna().sum()

url             0
slug_x          0
final_title     0
description     0
level           0
skills          0
final_rating    0
dtype: int64

In [32]:
course_ratings.head(10)

,url,slug_x,final_title,description,level,skills,final_rating
0,https://www.coursera.org/learn/machine-learning,machine-learning,Supervised Machine Learning: Regression and Cl...,In the first course of the Machine Learning Sp...,Beginner,"[Jupyter, PredictiveModeling, PythonProgrammin...",4.90
1,https://www.coursera.org/learn/indigenous-canada,indigenous-canada,Indigenous Canada,Indigenous Canada is a 12-lesson Massive Open ...,Mixed,"[Socioeconomics, Governance, PoliticalSciences...",4.82
2,https://www.coursera.org/learn/the-science-of-...,the-science-of-well-being,The Science of Well-Being,NEW TEEN VERSION AVAILABLE HERE: https://www.c...,Mixed,"[GrowthMindedness, CognitiveBehavioralTherapy,...",4.90
3,https://www.coursera.org/learn/technical-suppo...,technical-support-fundamentals,Technical Support Fundamentals,"In this course, youâll be introduced to the ...",Beginner,"[HardwareTroubleshooting, SystemSoftware, Tech...",4.83
4,https://www.coursera.org/learn/google-cbrs-cpi...,google-cbrs-cpi-training,google cbrs cpi training,No description,Beginner,"[PublicKeyInfrastructure, SystemConfiguration,...",4.10
5,https://www.coursera.org/learn/financial-marke...,financial-markets-global,Financial Markets,"An overview of the ideas, methods, and institu...",Beginner,"[CapitalMarkets, Finance, FinancialMarket, Der...",4.81
6,https://www.coursera.org/learn/introduction-ps...,introduction-psychology,Introduction to Psychology,What are people most afraid of? What do our dr...,Beginner,"[Sociology, HumanDevelopment, SocialSciences, ...",4.86
7,https://www.coursera.org/learn/python,python,Programming for Everybody (Getting Started wit...,This course aims to teach everyone the basics ...,Beginner,"[ComputerProgramming, SoftwareInstallation, De...",4.83
8,https://www.coursera.org/learn/computer-networ...,computer-networking,The Bits and Bytes of Computer Networking,This course is designed to provide a full over...,Beginner,"[DynamicHostConfigurationProtocol(DHCP), Netwo...",4.72
9,https://www.coursera.org/learn/ai-for-everyone,ai-for-everyone,AI For Everyone,AI is not only for engineers. If you want your...,Beginner,"[StrategicThinking, ArtificialIntelligence, De...",4.79

In [33]:
course_ratings['description']=course_ratings['description'].apply(lambda x:x.split())

In [34]:
course_ratings['slug_x']=course_ratings['slug_x'].str.replace('-',' ').apply(lambda x:x.split())

In [35]:
course_ratings.head()

,url,slug_x,final_title,description,level,skills,final_rating
0,https://www.coursera.org/learn/machine-learning,"[machine, learning]",Supervised Machine Learning: Regression and Cl...,"[In, the, first, course, of, the, Machine, Lea...",Beginner,"[Jupyter, PredictiveModeling, PythonProgrammin...",4.90
1,https://www.coursera.org/learn/indigenous-canada,"[indigenous, canada]",Indigenous Canada,"[Indigenous, Canada, is, a, 12-lesson, Massive...",Mixed,"[Socioeconomics, Governance, PoliticalSciences...",4.82
2,https://www.coursera.org/learn/the-science-of-...,"[the, science, of, well, being]",The Science of Well-Being,"[NEW, TEEN, VERSION, AVAILABLE, HERE:, https:/...",Mixed,"[GrowthMindedness, CognitiveBehavioralTherapy,...",4.90
3,https://www.coursera.org/learn/technical-suppo...,"[technical, support, fundamentals]",Technical Support Fundamentals,"[In, this, course,, youâll, be, introduced, ...",Beginner,"[HardwareTroubleshooting, SystemSoftware, Tech...",4.83
4,https://www.coursera.org/learn/google-cbrs-cpi...,"[google, cbrs, cpi, training]",google cbrs cpi training,"[No, description]",Beginner,"[PublicKeyInfrastructure, SystemConfiguration,...",4.10

In [36]:
course_ratings['tags']=course_ratings['slug_x']+course_ratings['description']+course_ratings['skills']

In [37]:
course_ratings.head()

,url,slug_x,final_title,description,level,skills,final_rating,tags
0,https://www.coursera.org/learn/machine-learning,"[machine, learning]",Supervised Machine Learning: Regression and Cl...,"[In, the, first, course, of, the, Machine, Lea...",Beginner,"[Jupyter, PredictiveModeling, PythonProgrammin...",4.90,"[machine, learning, In, the, first, course, of..."
1,https://www.coursera.org/learn/indigenous-canada,"[indigenous, canada]",Indigenous Canada,"[Indigenous, Canada, is, a, 12-lesson, Massive...",Mixed,"[Socioeconomics, Governance, PoliticalSciences...",4.82,"[indigenous, canada, Indigenous, Canada, is, a..."
2,https://www.coursera.org/learn/the-science-of-...,"[the, science, of, well, being]",The Science of Well-Being,"[NEW, TEEN, VERSION, AVAILABLE, HERE:, https:/...",Mixed,"[GrowthMindedness, CognitiveBehavioralTherapy,...",4.90,"[the, science, of, well, being, NEW, TEEN, VER..."
3,https://www.coursera.org/learn/technical-suppo...,"[technical, support, fundamentals]",Technical Support Fundamentals,"[In, this, course,, youâll, be, introduced, ...",Beginner,"[HardwareTroubleshooting, SystemSoftware, Tech...",4.83,"[technical, support, fundamentals, In, this, c..."
4,https://www.coursera.org/learn/google-cbrs-cpi...,"[google, cbrs, cpi, training]",google cbrs cpi training,"[No, description]",Beginner,"[PublicKeyInfrastructure, SystemConfiguration,...",4.10,"[google, cbrs, cpi, training, No, description,..."

In [38]:
new_df=course_ratings[['url','final_title','tags','level','final_rating']]
new_df

,url,final_title,tags,level,final_rating
0,https://www.coursera.org/learn/machine-learning,Supervised Machine Learning: Regression and Cl...,"[machine, learning, In, the, first, course, of...",Beginner,4.90
1,https://www.coursera.org/learn/indigenous-canada,Indigenous Canada,"[indigenous, canada, Indigenous, Canada, is, a...",Mixed,4.82
2,https://www.coursera.org/learn/the-science-of-...,The Science of Well-Being,"[the, science, of, well, being, NEW, TEEN, VER...",Mixed,4.90
3,https://www.coursera.org/learn/technical-suppo...,Technical Support Fundamentals,"[technical, support, fundamentals, In, this, c...",Beginner,4.83
4,https://www.coursera.org/learn/google-cbrs-cpi...,google cbrs cpi training,"[google, cbrs, cpi, training, No, description,...",Beginner,4.10
...,...,...,...,...,...
620,https://www.coursera.org/learn/accounting-data...,Accounting Data Analytics with Python,"[accounting, data, analytics, python, This, co...",Intermediate,4.41
621,https://www.coursera.org/learn/spectroscopy,Introduction to Molecular Spectroscopy,"[spectroscopy, The, course, introduces, the, t...",Intermediate,4.70
622,https://www.coursera.org/learn/managing-as-a-c...,Managing as a Coach,"[managing, as, a, coach, Do, you, (or, do, you...",Mixed,4.79
623,https://www.coursera.org/learn/hotel-distribution,hotel distribution,"[hotel, distribution, No, description, Strateg...",Beginner,4.61
624,https://www.coursera.org/learn/data-science-co...,data science course,"[data, science, course, No, description, DataM...",Beginner,4.46

In [39]:
new_df['tags']=new_df['tags'].apply(lambda x: ' '.join(x))

In [40]:
new_df['tags']=new_df['tags'].apply(lambda x: x.lower())

In [41]:
new_df

,url,final_title,tags,level,final_rating
0,https://www.coursera.org/learn/machine-learning,Supervised Machine Learning: Regression and Cl...,machine learning in the first course of the ma...,Beginner,4.90
1,https://www.coursera.org/learn/indigenous-canada,Indigenous Canada,indigenous canada indigenous canada is a 12-le...,Mixed,4.82
2,https://www.coursera.org/learn/the-science-of-...,The Science of Well-Being,the science of well being new teen version ava...,Mixed,4.90
3,https://www.coursera.org/learn/technical-suppo...,Technical Support Fundamentals,"technical support fundamentals in this course,...",Beginner,4.83
4,https://www.coursera.org/learn/google-cbrs-cpi...,google cbrs cpi training,google cbrs cpi training no description public...,Beginner,4.10
...,...,...,...,...,...
620,https://www.coursera.org/learn/accounting-data...,Accounting Data Analytics with Python,accounting data analytics python this course f...,Intermediate,4.41
621,https://www.coursera.org/learn/spectroscopy,Introduction to Molecular Spectroscopy,spectroscopy the course introduces the three k...,Intermediate,4.70
622,https://www.coursera.org/learn/managing-as-a-c...,Managing as a Coach,managing as a coach do you (or do you want to)...,Mixed,4.79
623,https://www.coursera.org/learn/hotel-distribution,hotel distribution,hotel distribution no description strategicpar...,Beginner,4.61
624,https://www.coursera.org/learn/data-science-co...,data science course,data science course no description datamanagem...,Beginner,4.46

In [42]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [43]:
def stemming(obj):
    y=[]
    for i in obj.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [44]:
new_df['tags']=new_df['tags'].apply(stemming)

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features=5000, stop_words='english',ngram_range=(1,2))
vectors=cv.fit_transform(new_df['tags']).toarray()

In [46]:
vectors

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
def get_user_input():
    print("Welcome to the course recommeder!")
    user_skill=input("Which skill do you want to learn? (e.g., Python, Machine Learning, Leadership): ").lower()
    user_difficulty = input("2. What level of difficulty are you looking for? (Beginner, Intermediate, Mixed): ").lower()
    user_description = input("3. Describe the kind of course you want (e.g., 'practical applications', 'theoretical concepts', 'project-based'): ").lower()
    return user_skill,user_difficulty,user_description

In [48]:
def query_vectorizer(user_skill,user_description,ps,cv):
    user_query=f"{user_skill} {user_skill} {user_skill} {user_description}"
    stemmed_query=stemming(user_query)
    user_vector=cv.transform([stemmed_query]).toarray()
    return user_vector

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
def recommend_courses(user_vector,new_df,user_difficulty,course_vectors=vectors,num_recs=5,rating_threshold=3.5):
    similarities = cosine_similarity(user_vector,course_vectors).flatten()
    sorted_indices=similarities.argsort()[::-1]
    recommendations=[]
    rec_count=0
    min_rating=new_df['final_rating'].min()
    max_rating = new_df['final_rating'].max()
    rating_boosts = ((new_df['final_rating'] - min_rating) / (max_rating - min_rating)).fillna(0) + 0.5
    print(f"\nSearching for {user_difficulty.capitalize()} courses...")
    print(f"Minimum rating considered: {rating_threshold}")
    for idx in sorted_indices:
        course_title=new_df.iloc[idx]['final_title']
        course_difficulty=new_df.iloc[idx]['level'].lower()
        course_rating = new_df.iloc[idx]['final_rating']
        raw_similarity = similarities[idx]
        if user_difficulty != 'mixed' and course_difficulty != user_difficulty:
            continue
        if course_rating < rating_threshold:
            continue
        final_score = (raw_similarity * 0.9) + (rating_boosts.iloc[idx] * 0.1)
        recommendations.append({
            'title': course_title,
            'url': new_df.iloc[idx]['url'],
            'difficulty': course_difficulty.capitalize(),
            'average_rating': course_rating,
            'similarity_score': raw_similarity,
            'final_ranking_score': final_score
        })
        rec_count += 1
        if rec_count >= num_recs:
            break
    recommendations = sorted(recommendations, key=lambda x: x['final_ranking_score'], reverse=True)
    if not recommendations:
        print("No courses found matching your criteria. Try different inputs.")
        return pd.DataFrame()

    return pd.DataFrame(recommendations)

In [53]:
def recommendation_system():
    user_skill,user_difficulty,user_description=get_user_input()
    user_vector=query_vectorizer(user_skill,user_description,ps,cv)
    recommendations_df = recommend_courses(user_vector,new_df,user_difficulty)
    if not recommendations_df.empty:
        print("\n--- Your Recommended Courses ---")
        print(recommendations_df[['title', 'difficulty', 'average_rating', 'url', 'final_ranking_score']].to_string(index=False))
    else:
        print("Sorry, we couldn't find any recommendations based on your input.")
if __name__ == "__main__":
    recommendation_system()

Welcome to the course recommeder!
Which skill do you want to learn? (e.g., Python, Machine Learning, Leadership): machine learning
2. What level of difficulty are you looking for? (Beginner, Intermediate, Mixed): mixed
3. Describe the kind of course you want (e.g., 'practical applications', 'theoretical concepts', 'project-based'): practical

Searching for Mixed courses...
Minimum rating considered: 3.5

--- Your Recommended Courses ---
                                                     title   difficulty  average_rating                                                         url  final_ranking_score
Supervised Machine Learning: Regression and Classification     Beginner            4.90             https://www.coursera.org/learn/machine-learning             0.696189
                     Structuring Machine Learning Projects     Beginner            4.79    https://www.coursera.org/learn/machine-learning-projects             0.611409
                                  Machine Learning for All     Beginner            4.68 https://www.coursera.org/learn/uol-machine-learning-for-all             0.584408
                          Introduction to Machine Learning Intermediate            4.67        https://www.coursera.org/learn/machine-learning-duke             0.503625
                        Applied Machine Learning in Python Intermediate            4.60      https://www.coursera.org/learn/python-machine-learning             0.465330

In [52]:
import pickle

# Saving the processed dataframe
pickle.dump(new_df, open('course_list.pkl', 'wb'))

# Downloading the file to the Chromebook
from google.colab import files
files.download('course_list.pkl')